### ISSUE TITLE
Could not find block when fork network

### ISSUE THREAD

**Issue by berlinp-wombat** [matter-labs/era-test-node#190]
#### 📝 Description

I am trying to fork `mainnet` with command `era_test_node fork mainnet`
But always get this error
```
thread 'main' panicked at src/fork.rs:311:17:
Could not find block #16665656 (0x4cc58c0d37f08bf24a1c83b61ce41b878e1d00d8295fce3e10258ecc3c246dfd) in "https://mainnet.era.zksync.io:443"
```
Also try to put the `--fork-at` argument but still get the same err
Failed with `era_test_node fork testnet` too

#### 🖥️ Environment

- **era-test-node version**: [era-test-node-v0.1.0-alpha.7-aarch64-apple-darwin.tar.gz](https://github.com/matter-labs/era-test-node/releases/download/v0.1.0-alpha.7/era_test_node-v0.1.0-alpha.7-aarch64-apple-darwin.tar.gz)
- **Operating System & Version**:  macOS 12.2

#### 📎 Log Output

```
RUST_BACKTRACE=full era_test_node fork mainnet
thread 'main' panicked at src/fork.rs:311:17:
Could not find block #16666275 (0xcbb4282a22169d8a441a0b9db0d40168cc639c4c724ee20a4bd0e3a1dd33a2e2) in "https://mainnet.era.zksync.io:443"
stack backtrace:
   0:        0x1013a3050 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4268b2ed62fb94
   1:        0x1013c2148 - core::fmt::write::h5d55d44549819258
   2:        0x1013a0310 - std::io::Write::write_fmt::hc515897f91abd6cf
   3:        0x1013a2e90 - std::sys_common::backtrace::print::h2c300c1ebedfc73c
   4:        0x1013a44f0 - std::panicking::default_hook::{{closure}}::h0aa9be5c44269370
   5:        0x1013a421c - std::panicking::default_hook::h2c0ef097934ee9e6
   6:        0x1013a4a38 - std::panicking::rust_panic_with_hook::h84c8637cb6e56008
   7:        0x1013a4944 - std::panicking::begin_panic_handler::{{closure}}::h25482adda06c7b7f
   8:        0x1013a34dc - std::sys_common::backtrace::__rust_end_short_backtrace::h0c6f3beb22324a29
   9:        0x1013a46a8 - _rust_begin_unwind
  10:        0x1014083f8 - core::panicking::panic_fmt::h9072a0246ecafd14
  11:        0x100b244ac - era_test_node::fork::ForkDetails<era_test_node::http_fork_source::HttpForkSource>::from_url_and_miniblock_and_chain::{{closure}}::hd3ba8f26c6e44228
  12:        0x100b2fcc0 - era_test_node::main::{{closure}}::h0ce5ccbd3dc13c11
  13:        0x100b16c5c - tokio::runtime::park::CachedParkThread::block_on::he9a238f63f232a69
  14:        0x100b19c30 - tokio::runtime::context::runtime::enter_runtime::h233e6973428e368c
  15:        0x100b6d3d0 - tokio::runtime::runtime::Runtime::block_on::h356f5473fded66eb
  16:        0x100b2f128 - era_test_node::main::heb6ea11c4cadf0b6
  17:        0x100b5d3dc - std::sys_common::backtrace::__rust_begin_short_backtrace::hd51efb66eb19a7b0
  18:        0x100d260cc - std::rt::lang_start::{{closure}}::h3bd6d8a7b9171166
  19:        0x10139a720 - std::rt::lang_start_internal::hadaf077a6dd0140b
  20:        0x100b31a30 - _main
```

**Comment by MexicanAce** [comment]
This might be related to the latest release of `zksync-era` upstream... I'll take a closer look and we'll probably have to update the version again to match. If this is the case, I'll start a new release to get this fixed for everyone
