### ISSUE TITLE
String returned by `web3_clientVersion` causes `hardhat-network-helpers` methods to throw OnlyHardhatNetworkError

### ISSUE THREAD

**Issue by gabspeck** [matter-labs/era-test-node#317]
#### 📝 Description

The string returned by the `web3_clientVersion` RPC method (`zkSync/2.0`) is not compatible with [a check made by the `hardhat-network-helpers` package](https://github.com/NomicFoundation/hardhat/blob/f579adca83f0a4c47bf29cd5df9ebc9347443039/packages/hardhat-network-helpers/src/utils.ts#L21):

```typescript
async function checkIfDevelopmentNetwork(
  provider: EIP1193Provider,
  networkName: string
): Promise<boolean> {
  let version: string | undefined;
  if (cachedIsDevelopmentNetwork === undefined) {
    try {
      version = (await provider.request({
        method: "web3_clientVersion",
      })) as string;

      cachedIsDevelopmentNetwork =
        version.toLowerCase().startsWith("hardhatnetwork") ||
        version.toLowerCase().startsWith("anvil");
    } catch (e) {
      cachedIsDevelopmentNetwork = false;
    }
  }

  if (!cachedIsDevelopmentNetwork) {
    throw new OnlyHardhatNetworkError(networkName, version);
  }

  return cachedIsDevelopmentNetwork;
}
```

#### 🔄 Reproduction Steps
1. Create a zksync project: `npx zksync-cli create demo --template hardhat_solidity`
2. Add the `@nomicfoundation/hardhat-network-helpers` dependency
3. Create the following test and run it:

```typescript
import { mine, takeSnapshot } from "@nomicfoundation/hardhat-network-helpers";

describe.only("hardhat-network-helpers bug repro", () => {
  it("should mine successfully", async () => {
	await mine()
  });
  it("should take a snapshot", async () => {
	await takeSnapshot()
  });
});
```

#### 🤔 Expected Behavior

The tests pass.

#### 😯 Current Behavior
Tests fail with the following output:
```
  hardhat-network-helpers bug repro
    1) should mine successfully
    2) should take a snapshot


  0 passing (8ms)
  2 failing

  1) hardhat-network-helpers bug repro
       should mine successfully:
     OnlyHardhatNetworkError: This helper can only be used with Hardhat Network. You are connected to 'zkSyncEraTestNode', whose identifier is 'zkSync/v2.0'
      at checkIfDevelopmentNetwork (/Users/gabriel/projetos/demo/node_modules/@nomicfoundation/hardhat-network-helpers/src/utils.ts:29:11)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async getHardhatProvider (/Users/gabriel/projetos/demo/node_modules/@nomicfoundation/hardhat-network-helpers/src/utils.ts:40:3)
      at async mine (/Users/gabriel/projetos/demo/node_modules/@nomicfoundation/hardhat-network-helpers/src/helpers/mine.ts:14:20)
      at async Context.<anonymous> (/Users/gabriel/projetos/demo/test/repro.test.ts:5:2)

  2) hardhat-network-helpers bug repro
       should take a snapshot:
     OnlyHardhatNetworkError: This helper can only be used with Hardhat Network. You are connected to 'zkSyncEraTestNode'.
      at checkIfDevelopmentNetwork (/Users/gabriel/projetos/demo/node_modules/@nomicfoundation/hardhat-network-helpers/src/utils.ts:29:11)
      at getHardhatProvider (/Users/gabriel/projetos/demo/node_modules/@nomicfoundation/hardhat-network-helpers/src/utils.ts:40:9)
      at async takeSnapshot (/Users/gabriel/projetos/demo/node_modules/@nomicfoundation/hardhat-network-helpers/src/helpers/takeSnapshot.ts:20:20)
      at async Context.<anonymous> (/Users/gabriel/projetos/demo/test/repro.test.ts:8:2)
```
#### 🖥️ Environment

- **Operating System & Version**: MacOS 
- **Other relevant environment details**: tested with the latest release (`era_test_node 0.1.0-alpha.25`)

#### 📋 Additional Context

The `hardhat-network-helpers` dependency is used by packages like the [OpenZeppelin test helpers](https://docs.openzeppelin.com/test-helpers/0.5/api#time)

**Comment by MexicanAce** [comment]
The hardhat network helpers npm package has hard coded logic to only work with their local Hardhat Network. So I believe this would require in that upstream npm package

**Comment by MexicanAce** [comment]
As resolving this issue would require upstream changes to the `hardhat-network-helpers` repo, I'm closing this issue for now
